"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import {
  DemoCard,
  DemoInfo,
  DemoShell,
  demoNavItems,
} from "@/components/demo/DemoShell";
import {
  DEMO_STORAGE_KEY,
  calculateObjectiveScore,
  demoAssignment,
  demoQuestions,
} from "@/components/demo/scenario";

const EXAM_SECONDS = demoAssignment.durationMin * 60;

export default function DemoStudentAttemptPage() {
  const [assignmentId, setAssignmentId] = useState(demoAssignment.id);

  const [studentName, setStudentName] = useState("Roman V.");
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [openAnswer, setOpenAnswer] = useState(
    "Because a real symmetric matrix has real eigenvalues and orthogonal eigenspaces. By spectral theorem it can be diagonalized with an orthonormal basis."
  );
  const [timeLeft, setTimeLeft] = useState(EXAM_SECONDS);
  const [started, setStarted] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [submissionId, setSubmissionId] = useState<string | null>(null);
  const [objectiveScore, setObjectiveScore] = useState(0);
  const [objectiveMax, setObjectiveMax] = useState(0);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const value = params.get("assignment");
    if (value) {
      setAssignmentId(value);
    }
  }, []);

  useEffect(() => {
    const timer = window.setInterval(() => {
      setTimeLeft((prev) => {
        if (!started || submitted) return prev;
        if (prev <= 0) return 0;
        return prev - 1;
      });
    }, 1000);
    return () => window.clearInterval(timer);
  }, [started, submitted]);

  const answeredCount = useMemo(() => {
    let count = 0;
    for (const q of demoQuestions) {
      if (q.kind === "single" && answers[q.id]) count += 1;
      if (q.kind === "open" && openAnswer.trim()) count += 1;
    }
    return count;
  }, [answers, openAnswer]);

  const canSubmit = started && !submitted && answeredCount >= 2;

  const submitAttempt = () => {
    if (!canSubmit) return;

    const objective = calculateObjectiveScore(answers);
    const newId = `att-${Date.now()}`;

    setObjectiveScore(objective.score);
    setObjectiveMax(objective.max);
    setSubmissionId(newId);
    setSubmitted(true);

    if (typeof window !== "undefined") {
      const payload = {
        id: newId,
        studentName: studentName.trim() || "Student",
        assignmentId,
        objectiveScore: objective.score,
        objectiveMax: objective.max,
        openAnswer: openAnswer.trim(),
        openMax: 8,
        status: "submitted",
        submittedAt: new Date().toISOString(),
      };
      window.localStorage.setItem(DEMO_STORAGE_KEY, JSON.stringify(payload));
    }
  };

  const updateSingleAnswer = (questionId: string, option: string) => {
    if (submitted) return;
    setAnswers((prev) => ({ ...prev, [questionId]: option }));
  };

  const minutes = Math.floor(timeLeft / 60);
  const seconds = timeLeft % 60;

  return (
    <DemoShell
      title="Student Test Window"
      subtitle="This endpoint simulates the student experience after opening the assignment link generated by teacher AI Studio."
      roleBadge="Role: Student"
      navItems={demoNavItems}
      activeHref="/demo-flow/student-attempt"
    >
      <div className="grid gap-5 xl:grid-cols-5">
        <div className="space-y-5 xl:col-span-3">
          <DemoCard title="Student Info" subtitle="Different role and UI from teacher dashboard.">
            <label className="text-sm">
              <span className="text-slate-300">Student name</span>
              <input
                value={studentName}
                onChange={(e) => setStudentName(e.target.value)}
                disabled={submitted}
                className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900/75 px-3 py-2 text-white outline-none focus:border-amber-300/55 disabled:opacity-70"
              />
            </label>

            <div className="mt-4 flex flex-wrap gap-2">
              <button
                type="button"
                disabled={started || submitted}
                onClick={() => setStarted(true)}
                className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50"
              >
                {started ? "Started" : "Start test"}
              </button>
              <button
                type="button"
                disabled={!canSubmit}
                onClick={submitAttempt}
                className="rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50"
              >
                Submit attempt
              </button>
            </div>
          </DemoCard>

          <DemoCard title="Questions" subtitle="Objective answers are auto-scored. Open answer is sent for AI-assisted teacher review.">
            <div className="space-y-4">
              {demoQuestions.map((question, index) => (
                <div key={question.id} className="rounded-xl border border-slate-700 bg-slate-900/70 p-3 text-sm">
                  <p className="font-semibold text-white">
                    Q{index + 1}. {question.text}
                  </p>

                  {question.kind === "single" && question.options ? (
                    <div className="mt-3 grid gap-2">
                      {question.options.map((option) => {
                        const selected = answers[question.id] === option;
                        return (
                          <button
                            key={option}
                            type="button"
                            disabled={!started || submitted}
                            onClick={() => updateSingleAnswer(question.id, option)}
                            className={`rounded-lg border px-3 py-2 text-left ${
                              selected
                                ? "border-amber-300/60 bg-amber-500/16 text-amber-100"
                                : "border-slate-600 bg-slate-800/70 text-slate-200"
                            } disabled:opacity-70`}
                          >
                            {option}
                          </button>
                        );
                      })}
                    </div>
                  ) : null}

                  {question.kind === "open" ? (
                    <textarea
                      rows={5}
                      value={openAnswer}
                      onChange={(e) => setOpenAnswer(e.target.value)}
                      disabled={!started || submitted}
                      className="mt-3 w-full rounded-lg border border-slate-600 bg-slate-800/70 px-3 py-2 text-slate-100 outline-none focus:border-amber-300/55 disabled:opacity-70"
                    />
                  ) : null}
                </div>
              ))}
            </div>
          </DemoCard>
        </div>

        <div className="space-y-5 xl:col-span-2">
          <DemoCard title="Attempt Status" subtitle="Live student panel for video.">
            <div className="space-y-3 text-sm">
              <DemoInfo label="Assignment" value={assignmentId} />
              <DemoInfo label="Timer" value={`${minutes}:${String(seconds).padStart(2, "0")}`} highlight={timeLeft < 180} />
              <DemoInfo label="Answered" value={`${answeredCount} / ${demoQuestions.length}`} />
              <DemoInfo label="State" value={submitted ? "Submitted" : started ? "In progress" : "Not started"} />
              {submitted ? <DemoInfo label="Submission ID" value={submissionId || "pending"} /> : null}
            </div>
          </DemoCard>

          {submitted ? (
            <DemoCard title="Submission Result" subtitle="Objective part is graded instantly; open answer goes to teacher with AI helper.">
              <div className="space-y-3 text-sm text-slate-200">
                <DemoInfo label="Objective score" value={`${objectiveScore} / ${objectiveMax}`} />
                <DemoInfo label="Open answer" value="Pending teacher + AI review" />
                <Link
                  href={`/demo-flow/teacher-review?assignment=${assignmentId}&attempt=${submissionId || "latest"}`}
                  className="inline-flex rounded-lg bg-indigo-400 px-4 py-2 font-semibold text-slate-950"
                >
                  Open teacher review endpoint
                </Link>
              </div>
            </DemoCard>
          ) : (
            <DemoCard title="What Happens Next" subtitle="For recording narrative.">
              <p className="text-sm text-slate-300">
                After submission, objective answers are scored automatically and the open response is sent to teacher review where AI suggests a rubric-based score.
              </p>
            </DemoCard>
          )}
        </div>
      </div>
    </DemoShell>
  );
}
