'use client';

import React, { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { TestService } from '@/services/test';
import { CreateTestRequest, QuestionFormData, AnswerFormData } from '@/types/test';

interface CreateTestFormProps {
  onSuccess?: () => void;
  onCancel?: () => void;
}

export default function CreateTestForm({ onSuccess, onCancel }: CreateTestFormProps) {
  const { user } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    questions: [
      {
        question_text: '',
        options: [
          { answer_text: '' },
          { answer_text: '' }
        ],
        correct_option: 0,
        image_url: ''
      }
    ] as QuestionFormData[]
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;

    setIsSubmitting(true);
    setError(null);

    try {
      // Convert form data to match backend format
      const testData: CreateTestRequest = {
        author: `${user.first_name} ${user.last_name}`,
        title: formData.title,
        description: formData.description,
        questions: formData.questions.map((q, qIndex) => ({
          id: '', // Will be generated by backend
          question_text: q.question_text,
          options: q.options.map((opt, optIndex) => ({
            answer: optIndex,
            answer_text: opt.answer_text,
            image_url: opt.image_url
          })),
          correct_option: q.correct_option,
          image_url: q.image_url
        }))
      };

      const response = await TestService.createTest(testData);
      
      if (response.success) {
        onSuccess?.();
      } else {
        setError(response.error || 'Failed to create test');
      }
    } catch (err) {
      setError('An unexpected error occurred');
    } finally {
      setIsSubmitting(false);
    }
  };

  const addQuestion = () => {
    setFormData(prev => ({
      ...prev,
      questions: [
        ...prev.questions,
        {
          question_text: '',
          options: [
            { answer_text: '' },
            { answer_text: '' }
          ],
          correct_option: 0,
          image_url: ''
        }
      ]
    }));
  };

  const removeQuestion = (index: number) => {
    if (formData.questions.length > 1) {
      setFormData(prev => ({
        ...prev,
        questions: prev.questions.filter((_, i) => i !== index)
      }));
    }
  };

  const updateQuestion = (questionIndex: number, field: string, value: any) => {
    setFormData(prev => ({
      ...prev,
      questions: prev.questions.map((q, i) => 
        i === questionIndex ? { ...q, [field]: value } : q
      )
    }));
  };

  const addOption = (questionIndex: number) => {
    setFormData(prev => ({
      ...prev,
      questions: prev.questions.map((q, i) => 
        i === questionIndex 
          ? { ...q, options: [...q.options, { answer_text: '' }] }
          : q
      )
    }));
  };

  const removeOption = (questionIndex: number, optionIndex: number) => {
    if (formData.questions[questionIndex].options.length > 2) {
      setFormData(prev => ({
        ...prev,
        questions: prev.questions.map((q, i) => 
          i === questionIndex 
            ? { 
                ...q, 
                options: q.options.filter((_, oi) => oi !== optionIndex),
                correct_option: q.correct_option >= optionIndex && q.correct_option > 0 
                  ? q.correct_option - 1 
                  : q.correct_option
              }
            : q
        )
      }));
    }
  };

  const updateOption = (questionIndex: number, optionIndex: number, value: string) => {
    setFormData(prev => ({
      ...prev,
      questions: prev.questions.map((q, i) => 
        i === questionIndex 
          ? { 
              ...q, 
              options: q.options.map((opt, oi) => 
                oi === optionIndex ? { ...opt, answer_text: value } : opt
              )
            }
          : q
      )
    }));
  };

  return (
    <div className="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Create New Test</h2>
      
      {error && (
        <div className="mb-4 p-4 text-red-700 bg-red-100 border border-red-300 rounded-md">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Test Title */}
        <div>
          <label htmlFor="title" className="block text-sm font-medium text-gray-700 mb-2">
            Test Title *
          </label>
          <input
            type="text"
            id="title"
            required
            value={formData.title}
            onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            placeholder="Enter test title"
          />
        </div>

        {/* Test Description */}
        <div>
          <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-2">
            Description *
          </label>
          <textarea
            id="description"
            required
            rows={3}
            value={formData.description}
            onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
            placeholder="Enter test description"
          />
        </div>

        {/* Questions */}
        <div>
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Questions</h3>
            <button
              type="button"
              onClick={addQuestion}
              className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            >
              Add Question
            </button>
          </div>

          {formData.questions.map((question, questionIndex) => (
            <div key={questionIndex} className="border border-gray-200 rounded-lg p-4 mb-4">
              <div className="flex justify-between items-center mb-3">
                <h4 className="font-medium text-gray-900">Question {questionIndex + 1}</h4>
                {formData.questions.length > 1 && (
                  <button
                    type="button"
                    onClick={() => removeQuestion(questionIndex)}
                    className="text-red-600 hover:text-red-800"
                  >
                    Remove
                  </button>
                )}
              </div>

              {/* Question Text */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Question Text *
                </label>
                <input
                  type="text"
                  required
                  value={question.question_text}
                  onChange={(e) => updateQuestion(questionIndex, 'question_text', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  placeholder="Enter question text"
                />
              </div>

              {/* Question Image URL */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Question Image URL (Optional)
                </label>
                <input
                  type="url"
                  value={question.image_url || ''}
                  onChange={(e) => updateQuestion(questionIndex, 'image_url', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  placeholder="https://example.com/image.jpg"
                />
              </div>

              {/* Options */}
              <div className="mb-4">
                <div className="flex justify-between items-center mb-2">
                  <label className="block text-sm font-medium text-gray-700">
                    Answer Options *
                  </label>
                  <button
                    type="button"
                    onClick={() => addOption(questionIndex)}
                    className="text-sm text-indigo-600 hover:text-indigo-800"
                  >
                    Add Option
                  </button>
                </div>

                {question.options.map((option, optionIndex) => (
                  <div key={optionIndex} className="flex items-center space-x-2 mb-2">
                    <input
                      type="radio"
                      name={`correct-${questionIndex}`}
                      checked={question.correct_option === optionIndex}
                      onChange={() => updateQuestion(questionIndex, 'correct_option', optionIndex)}
                      className="text-indigo-600"
                    />
                    <input
                      type="text"
                      required
                      value={option.answer_text}
                      onChange={(e) => updateOption(questionIndex, optionIndex, e.target.value)}
                      className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                      placeholder={`Option ${optionIndex + 1}`}
                    />
                    {question.options.length > 2 && (
                      <button
                        type="button"
                        onClick={() => removeOption(questionIndex, optionIndex)}
                        className="text-red-600 hover:text-red-800"
                      >
                        ×
                      </button>
                    )}
                  </div>
                ))}
                <p className="text-xs text-gray-500 mt-1">
                  Select the correct answer by clicking the radio button
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Submit Buttons */}
        <div className="flex justify-end space-x-4">
          {onCancel && (
            <button
              type="button"
              onClick={onCancel}
              className="px-6 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            >
              Cancel
            </button>
          )}
          <button
            type="submit"
            disabled={isSubmitting}
            className="px-6 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isSubmitting ? 'Creating...' : 'Create Test'}
          </button>
        </div>
      </form>
    </div>
  );
}
